baseURL = 'https://hissamshar.github.io/'
languageCode = 'en-us'
title = 'Hisam Shar'
theme = 'hugo-PaperMod'

[params.profileMode]
enabled = true
title = "Hisam Mehboob"
subtitle = "Aspiring Software Engineer · Passionate about C/C++, Open Source, and Linux"
imageUrl = "https://raw.githubusercontent.com/hissamshar/hissamshar.github.io/refs/heads/master/Cropped_Image.png"
imageTitle = "Profile Picture"
imageWidth = 200
imageHeight = 200

[[params.profileMode.buttons]]
  name = "Posts"
  url = "/posts"

[[params.profileMode.buttons]]
  name = "Archive"
  url = "/archives"

[[params.profileMode.buttons]]
  name = "Github"
  url = "https://github.com/hissamshar"

[[params.socialIcons]]
name = "<Github>"
url = "https://github.com/hissamshar"

[[params.socialIcons]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/hisam-mehboob-a0880b213/"

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1_000
threshold = 0.4
minMatchCharLength = 0
keys = [ "title", "permalink", "summary", "content" ]

[params]
ShowShareButtons = true
ShowToc =  true
ShowReadingTime = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
