baseURL = 'https://hissamshar.github.io/'
languageCode = 'en-us'
title = 'Hisam Shar'
theme = 'hugo-PaperMod'

[params.profileMode]
enabled = true
title = "Hisam Mehboob"
imageUrl = "https://media.licdn.com/dms/image/v2/D4D03AQE8umejFElsEA/profile-displayphoto-shrink_800_800/B4DZSdLXoNG8Ac-/0/1737803791985?e=1743033600&v=beta&t=44obSsRvTRep2EuC2Pthg89_OOkYTK3Px1edTrkn_U4"
imageTitle = "Profile Picture"
imageWidth = 170
imageHeight = 170

[[params.profileMode.buttons]]
  name = "Posts"
  url = "/content/posts"

[[params.profileMode.buttons]]
  name = "Archive"
  url = "/archive"

[[params.profileMode.buttons]]
  name = "Github"
  url = "https://github.com/hissamshar"

[[params.socialIcons]]
name = "<Github>"
url = "https://github.com/hissamshar"

[[params.socialIcons]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/hisam-mehboob-a0880b213/"

